/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressSnapshot {
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'pinCode' : string,
  'phone' : string,
}
export interface CartItem {
  'id' : bigint,
  'userId' : Principal,
  'productId' : bigint,
  'updatedAt' : Time,
  'addedAt' : Time,
  'quantity' : bigint,
}
export interface CartItemView {
  'id' : bigint,
  'title' : string,
  'productId' : bigint,
  'updatedAt' : Time,
  'addedAt' : Time,
  'quantity' : bigint,
  'salePrice' : [] | [number],
  'image' : string,
  'price' : number,
}
export type Category = { 'Home' : null } |
  { 'Grocery' : null } |
  { 'Books' : null } |
  { 'Fashion' : null } |
  { 'Electronics' : null };
export interface CreateAddressRequest {
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'isDefault' : boolean,
  'pinCode' : string,
  'phone' : string,
}
export interface CreateOrderRequest {
  'paymentMethod' : PaymentMethod,
  'shippingAddress' : AddressSnapshot,
}
export interface CreateReviewRequest {
  'title' : string,
  'body' : string,
  'productId' : bigint,
  'rating' : bigint,
  'images' : Array<string>,
}
export interface HelpfulVote { 'userId' : Principal, 'isHelpful' : boolean }
export interface Order {
  'id' : bigint,
  'trackingNumber' : [] | [string],
  'deliveryCharge' : number,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'userId' : Principal,
  'createdAt' : Time,
  'estimatedDeliveryDate' : [] | [Time],
  'updatedAt' : Time,
  'shippingAddress' : AddressSnapshot,
  'items' : Array<OrderItem>,
  'taxAmount' : number,
  'totalPrice' : number,
  'subtotal' : number,
}
export interface OrderItem {
  'title' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'image' : string,
  'price' : number,
}
export interface OrderNotification {
  'oldStatus' : OrderStatus,
  'userId' : Principal,
  'orderId' : bigint,
  'message' : string,
  'timestamp' : Time,
  'newStatus' : OrderStatus,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'outForDelivery' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'packed' : null } |
  { 'returned' : null };
export interface PaginatedOrders { 'total' : bigint, 'orders' : Array<Order> }
export type PaymentMethod = { 'COD' : null } |
  { 'UPI' : string } |
  { 'Card' : string };
export type PaymentStatus = { 'Failed' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : bigint,
  'sku' : string,
  'stockQuantity' : bigint,
  'title' : string,
  'description' : string,
  'sellerName' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'salePrice' : [] | [number],
  'brand' : string,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export interface RatingDistribution {
  'star1' : bigint,
  'star2' : bigint,
  'star3' : bigint,
  'star4' : bigint,
  'star5' : bigint,
}
export interface Review {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'productId' : bigint,
  'rating' : bigint,
  'helpfulVotes' : Array<HelpfulVote>,
  'helpfulCount' : bigint,
  'verifiedPurchase' : boolean,
  'images' : Array<string>,
}
export interface SearchParams {
  'categories' : Array<string>,
  'brands' : Array<string>,
  'minRating' : number,
  'inStock' : boolean,
  'sortBy' : string,
  'page' : bigint,
  'pageSize' : bigint,
  'maxPrice' : number,
  'minPrice' : number,
  'searchQuery' : string,
}
export interface SearchResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'products' : Array<Product>,
}
export type Time = bigint;
export interface UserAddress {
  'id' : bigint,
  'city' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'isDefault' : boolean,
  'pinCode' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], CartItem>,
  'cancelOrder' : ActorMethod<[bigint], [] | [Order]>,
  'clearCart' : ActorMethod<[], undefined>,
  'createAddress' : ActorMethod<[CreateAddressRequest], UserAddress>,
  'createOrder' : ActorMethod<[CreateOrderRequest], Order>,
  'createReview' : ActorMethod<[CreateReviewRequest], Review>,
  'getAllOrders' : ActorMethod<[bigint, bigint], PaginatedOrders>,
  'getBrands' : ActorMethod<[], Array<string>>,
  'getCart' : ActorMethod<[], Array<CartItemView>>,
  'getDeals' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderNotifications' : ActorMethod<[], Array<OrderNotification>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getRatingDistribution' : ActorMethod<[bigint], RatingDistribution>,
  'getSavedAddresses' : ActorMethod<[], Array<UserAddress>>,
  'getSearchSuggestions' : ActorMethod<[string], Array<Product>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'removeFromCart' : ActorMethod<[bigint], boolean>,
  'returnOrder' : ActorMethod<[bigint], [] | [Order]>,
  'searchProducts' : ActorMethod<[SearchParams], SearchResult>,
  'toggleHelpfulVote' : ActorMethod<[bigint, boolean], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], [] | [Order]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];