/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CartItem = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'productId' : IDL.Nat,
  'updatedAt' : Time,
  'addedAt' : Time,
  'quantity' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'UPI' : IDL.Text,
  'Card' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'packed' : IDL.Null,
  'returned' : IDL.Null,
});
export const AddressSnapshot = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'pinCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'deliveryCharge' : IDL.Float64,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'estimatedDeliveryDate' : IDL.Opt(Time),
  'updatedAt' : Time,
  'shippingAddress' : AddressSnapshot,
  'items' : IDL.Vec(OrderItem),
  'taxAmount' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const CreateAddressRequest = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'isDefault' : IDL.Bool,
  'pinCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserAddress = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'isDefault' : IDL.Bool,
  'pinCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const CreateOrderRequest = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'shippingAddress' : AddressSnapshot,
});
export const CreateReviewRequest = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const HelpfulVote = IDL.Record({
  'userId' : IDL.Principal,
  'isHelpful' : IDL.Bool,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
  'helpfulVotes' : IDL.Vec(HelpfulVote),
  'helpfulCount' : IDL.Nat,
  'verifiedPurchase' : IDL.Bool,
  'images' : IDL.Vec(IDL.Text),
});
export const PaginatedOrders = IDL.Record({
  'total' : IDL.Nat,
  'orders' : IDL.Vec(Order),
});
export const CartItemView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'productId' : IDL.Nat,
  'updatedAt' : Time,
  'addedAt' : Time,
  'quantity' : IDL.Nat,
  'salePrice' : IDL.Opt(IDL.Float64),
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const Category = IDL.Variant({
  'Home' : IDL.Null,
  'Grocery' : IDL.Null,
  'Books' : IDL.Null,
  'Fashion' : IDL.Null,
  'Electronics' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'salePrice' : IDL.Opt(IDL.Float64),
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const OrderNotification = IDL.Record({
  'oldStatus' : OrderStatus,
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
  'newStatus' : OrderStatus,
});
export const RatingDistribution = IDL.Record({
  'star1' : IDL.Nat,
  'star2' : IDL.Nat,
  'star3' : IDL.Nat,
  'star4' : IDL.Nat,
  'star5' : IDL.Nat,
});
export const SearchParams = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'brands' : IDL.Vec(IDL.Text),
  'minRating' : IDL.Float64,
  'inStock' : IDL.Bool,
  'sortBy' : IDL.Text,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'maxPrice' : IDL.Float64,
  'minPrice' : IDL.Float64,
  'searchQuery' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'products' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartItem], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'clearCart' : IDL.Func([], [], []),
  'createAddress' : IDL.Func([CreateAddressRequest], [UserAddress], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
  'createReview' : IDL.Func([CreateReviewRequest], [Review], []),
  'getAllOrders' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedOrders], ['query']),
  'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItemView)], ['query']),
  'getDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderNotifications' : IDL.Func(
      [],
      [IDL.Vec(OrderNotification)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getRatingDistribution' : IDL.Func(
      [IDL.Nat],
      [RatingDistribution],
      ['query'],
    ),
  'getSavedAddresses' : IDL.Func([], [IDL.Vec(UserAddress)], ['query']),
  'getSearchSuggestions' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'returnOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'searchProducts' : IDL.Func([SearchParams], [SearchResult], ['query']),
  'toggleHelpfulVote' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Opt(Order)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CartItem = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'productId' : IDL.Nat,
    'updatedAt' : Time,
    'addedAt' : Time,
    'quantity' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'COD' : IDL.Null,
    'UPI' : IDL.Text,
    'Card' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'packed' : IDL.Null,
    'returned' : IDL.Null,
  });
  const AddressSnapshot = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'pinCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'deliveryCharge' : IDL.Float64,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'orderStatus' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'estimatedDeliveryDate' : IDL.Opt(Time),
    'updatedAt' : Time,
    'shippingAddress' : AddressSnapshot,
    'items' : IDL.Vec(OrderItem),
    'taxAmount' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const CreateAddressRequest = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'isDefault' : IDL.Bool,
    'pinCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserAddress = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'isDefault' : IDL.Bool,
    'pinCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CreateOrderRequest = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'shippingAddress' : AddressSnapshot,
  });
  const CreateReviewRequest = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const HelpfulVote = IDL.Record({
    'userId' : IDL.Principal,
    'isHelpful' : IDL.Bool,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
    'helpfulVotes' : IDL.Vec(HelpfulVote),
    'helpfulCount' : IDL.Nat,
    'verifiedPurchase' : IDL.Bool,
    'images' : IDL.Vec(IDL.Text),
  });
  const PaginatedOrders = IDL.Record({
    'total' : IDL.Nat,
    'orders' : IDL.Vec(Order),
  });
  const CartItemView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'productId' : IDL.Nat,
    'updatedAt' : Time,
    'addedAt' : Time,
    'quantity' : IDL.Nat,
    'salePrice' : IDL.Opt(IDL.Float64),
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Category = IDL.Variant({
    'Home' : IDL.Null,
    'Grocery' : IDL.Null,
    'Books' : IDL.Null,
    'Fashion' : IDL.Null,
    'Electronics' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'salePrice' : IDL.Opt(IDL.Float64),
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const OrderNotification = IDL.Record({
    'oldStatus' : OrderStatus,
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
    'newStatus' : OrderStatus,
  });
  const RatingDistribution = IDL.Record({
    'star1' : IDL.Nat,
    'star2' : IDL.Nat,
    'star3' : IDL.Nat,
    'star4' : IDL.Nat,
    'star5' : IDL.Nat,
  });
  const SearchParams = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'brands' : IDL.Vec(IDL.Text),
    'minRating' : IDL.Float64,
    'inStock' : IDL.Bool,
    'sortBy' : IDL.Text,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'maxPrice' : IDL.Float64,
    'minPrice' : IDL.Float64,
    'searchQuery' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartItem], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'clearCart' : IDL.Func([], [], []),
    'createAddress' : IDL.Func([CreateAddressRequest], [UserAddress], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
    'createReview' : IDL.Func([CreateReviewRequest], [Review], []),
    'getAllOrders' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedOrders], ['query']),
    'getBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItemView)], ['query']),
    'getDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderNotifications' : IDL.Func(
        [],
        [IDL.Vec(OrderNotification)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRatingDistribution' : IDL.Func(
        [IDL.Nat],
        [RatingDistribution],
        ['query'],
      ),
    'getSavedAddresses' : IDL.Func([], [IDL.Vec(UserAddress)], ['query']),
    'getSearchSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'returnOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'searchProducts' : IDL.Func([SearchParams], [SearchResult], ['query']),
    'toggleHelpfulVote' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };