/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Home' : IDL.Null,
  'Grocery' : IDL.Null,
  'Books' : IDL.Null,
  'Fashion' : IDL.Null,
  'Electronics' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'salePrice' : IDL.Opt(IDL.Float64),
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Home' : IDL.Null,
    'Grocery' : IDL.Null,
    'Books' : IDL.Null,
    'Fashion' : IDL.Null,
    'Electronics' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'salePrice' : IDL.Opt(IDL.Float64),
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };