/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Home' : null } |
  { 'Grocery' : null } |
  { 'Books' : null } |
  { 'Fashion' : null } |
  { 'Electronics' : null };
export interface Product {
  'id' : bigint,
  'sku' : string,
  'stockQuantity' : bigint,
  'title' : string,
  'description' : string,
  'sellerName' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'salePrice' : [] | [number],
  'brand' : string,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export interface _SERVICE {
  'getDeals' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];